### ISSUE TITLE
How to define parameter when more than one phase ?

### ISSUE THREAD

**Issue by arima-sambunath** [geraintpalmer/Ciw-notebooks#2]
Hi All,

I have a discrete event simulation model of project (ticket raised when there is a issue of application ). let me describe bellow.

Total number of ticket  come after which divided into two phase(each phase having 50% tickets to solve) again each phase having more number of node lets say 3 nodes.

means under each phase ticket passes through each node for solution and finally closed.

Can any one help me to design parameter for this type of mode.

Thank You.

**Comment by geraintpalmer** [comment]
Hi @arima-sambunath would you mind explaining this again please? I'm not sure I understand what you are trying to do. Do you mean:

+ Tickets arrive
+ They then get split, 50% going to one direction and 50% another direction
+ At each direction the tickets go through a series of nodes before exiting the system

?

**Comment by arima-sambunath** [comment]
Hi @geraintpalmer ,

Thanks for your attention of my Question.
You are right and we both are in the same page, and each direction there may be any number of nodes.

**Comment by geraintpalmer** [comment]
A similar thing happens here: http://ciw.readthedocs.io/en/latest/Tutorial-II/tutorial_vii.html

You need to think about the system as a whole, rather than as 2 phases. Count how many nodes you have in total, and number them. Then they can be connected via `Transition_matrices`.

For example, a 6 node system, when customers arrive at one node, then split 50% go down a series of 3 nodes, and 50% go down another series of 2 nodes. Number the initial node as Node 1, The three nodes in series Nodes 2, 3 and 4, and the two nodes in series Nodes 5 and 6. The transition matrix for this would look like:

```
Transition_matrices=[
    [0.0, 0.5, 0.0, 0.0, 0.5, 0.0],
    [0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
]
```

**Comment by arima-sambunath** [comment]
Thank You very much, the example which really help help me a lot.

how can I add if I want one more distribution (Normal distribution) or are you added in latest release of ciw(1.0.0) .

**Comment by geraintpalmer** [comment]
Hi @arima-sambunath that's great to hear!

In the latest release the Truncated Normal distribution is available: http://ciw.readthedocs.io/en/latest/Reference/distributions.html#normal-dist

This is the same as the Normal distribution, but doesn't allow negative numbers to be sampled (as this would break the simulation). I hope this helps.

If you want to implement your own distributions, then Ciw has the `UserDefined` option too, to implement your own functions: http://ciw.readthedocs.io/en/latest/Reference/distributions.html#own-functions

**Comment by arima-sambunath** [comment]
Hi @geraintpalmer ,

Please correct me if I am wrong.

when we are setting Number_of_servers, lets say  'Number_of_servers': [1, 1, 1, 1] 
what I come to understand that I have system having 4 Node and each Node I am assigning only 1 server to each process.

Lets say a scenario where 2 Server  is shared among all the Node.
    Is this type of simulation possible by using Ciw library.

One more scenario : lets I have 100 instance to simulate  how can I know 
      Number of instance successfully simulate  and failure number.

**Comment by geraintpalmer** [comment]
Hi @arima-sambunath 

You are correct. Unfortunately at the moment there is no way for Nodes to share servers in Ciw :( If this is a feature you would like, please make an issue on the Ciw repo (https://github.com/CiwPython/Ciw/issues) requesting this feature. This might be a nice addition to the library in the future (although I can't see it happening soon sorry).

What do you mean by a simulation failing?

**Comment by arima-sambunath** [comment]
Lets say 1000 ticket come to at Node for processing . 
Is there a chance of rejection of ticket process ?

Lets say out of 1000 ticket 800 are process successfully remaining gone to reject list.

Let me put my idea . Please correct if any wrong.

Q.simulate_until_max_customers(no_ticket_coming, method='Accept') # simulate by passing 1000.
I think number of records return by   "Q.get_all_records()" with unique record_id are success number of simulation and remaining are rejected.

**Comment by mnips** [comment]
Hi @arima-sambunath ! Yes you are correct. The rejection as of what I can think will be only because of a baulking condition applied to that node. Q.get_all_records() will give you all the customers who have been accept by the system according to the simulation you have chosen. You can also get the list of the rejected customers from the rejection dictionary using the simulation object Q.rejection_dict.

**Comment by geraintpalmer** [comment]
Closing issue as I believe this has been solved.
